spring:
  profiles:
    active: developmentlocal
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
      max-active: 350
      initial-size: 10
      max-idle: 10
      min-idle: 0
      time-between-eviction-runs-millis: 30000
      remove-abandoned: true
      remove-abandoned-timeout: 60
      abandon-when-percentage-full: 100
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 30000
      log-abandoned: true
      test-on-connect: true
      test-on-return: true
      test-while-idle: true
      connection-test-query: SELECT 1
      auto-commit: false
      log-validation-errors: true

--- 
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none 
  datasource:
    url: jdbc:mysql://localhost:3306/agenda?autoReconnect=true
    username: root
    password: admin
